wmde/fundraising-payments

composer.json
Now possible since https://github.com/oradwell/covers-validator/releases/tag/v0.7.1
=> Use latest PHPUnit

src/Domain/BankDataValidator.php, tests/Unit/Domain/BankDataValidatorTest.php
Remove BIC and old-style bank data as a required fields.
Add test cases.
This is for https://phabricator.wikimedia.org/T192921
=> Simplify bank data validation

src/Domain/PaymentDataValidator.php, tests/Unit/Domain/PaymentDataValidatorTest.php
Removed payment type dependent minAmount because it is no longer needed.
Split paymentMethod validation and amountValidation into seperate methods.
=> refactor payment validator

src/Domain/Model/BankTransferPayment.php, src/Domain/Model/CreditCardPayment.php, src/Domain/Model/DirectDebitPayment.php, src/Domain/Model/PayPalPayment.php, src/Domain/Model/PaymentMethod.php, src/Domain/Model/PaymentWithoutAssociatedData.php, src/Domain/Model/SofortPayment.php, src/RequestModel/PayPalPaymentNotificationRequest.php
Force dates to be dates - they will be processed by the use cases having
a \DateTimeImmutable in there makes sure that the date is valid.
This is for https://phabricator.wikimedia.org/T235751
=> Change Notification request data type

src/Domain/Model/PayPalData.php
This getter is needed to store the child payment information in the
donation BLOB field. This helps developing a short-tem fix for
https://phabricator.wikimedia.org/T239644
Ideally, as tracked in https://phabricator.wikimedia.org/T192323, the
Payment domain keeps track of child payments itself so the other domains
don't need to.
=> Add getter for child payments

src/RequestModel/PayPalPaymentNotificationRequest.php
Changing the type to DateTimeImmutable but not PayPalData is
inconsistent. The changes necessary in donations,
memberships and FundraisingFrontend should be done in one fell swoop,
and not piece-by-piece.
This reverts commit eae1c5d2fb003b069e38cc8445d8ecbfc91d610d.
=> Revert "Change Notification request data type"

src/Domain/Model/CreditCardPayment.php, src/Domain/Model/PayPalPayment.php, tests/Unit/Domain/Model/CreditCardPaymentTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php
Follow up for https://github.com/wmde/fundraising-payments/pull/34 that adds real actual working checks for if the payment has been completed on PayPal and Credit Card payments.
=> Add real paymentCompleted checks on PP and CC

Makefile, src/Domain/PaymentUrlGenerator/PayPalConfig.php, tests/Unit/Domain/Model/CreditCardPaymentTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php
Adapted 2 tests and 2 doc block to make PHPStan pass on level 5.
For Level 6 we'd need type hints on all class properties and arrays.
=> Use PHPStan on Level 5

src/Domain/Model/BankTransferPayment.php, src/Domain/Model/BookablePayment.php, src/Domain/Model/CreditCardPayment.php, src/Domain/Model/CreditCardTransactionData.php, src/Domain/Model/DirectDebitPayment.php, src/Domain/Model/PayPalData.php, src/Domain/Model/PayPalPayment.php, src/Domain/Model/PaymentTransactionData.php, src/Domain/Model/PaymentWithoutAssociatedData.php, src/Domain/Model/SofortPayment.php, src/Domain/Model/SofortTransactionData.php, tests/Unit/Domain/Model/CreditCardPaymentTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php
The new interface marks payments as bookable and enables sending
different transaction data through the same method. It complements the
`paymentComplete` method.
The new interface will enable Donations to implement a unified
`bookDonation` method that both changes the internal state of the
donation and the payment, instead of having two discrete, independent
steps of booking the donation and then adding the payment data.
We can also use the interface in memberships if needed.
This is a step towards implementing a richer payment domain (see https://phabricator.wikimedia.org/T192323)
Added typehints to some classes.
=> Add new BookablePayment interface

.travis.yml
Don't ignore platform requirements on composer install to avoid
installing incompatible versions.
=> Improve composer install in CI

.travis.yml
In CI, we run PHPStan a second time to check if we're depending on test
code. The check level should match the check level for the first run.
=> Increase level for 2nd run of PHPStan

.gitignore, .scrutinizer.yml, .travis.yml, Makefile, docker-compose.debug.yml, docker-compose.yml
https://phabricator.wikimedia.org/T284180
Our old travis file tried to run PHPUnit after is was uninstalled,
leading to a missing coverage report file.
This change add coverage report output flags to the Makefile to
generate HTML by default and Clover XML when run through Travis.
=> Generate coverage report in CI

src/DataAccess/Sofort/Transfer/SofortLibClient.php, tests/Unit/DataAccess/Sofort/Transfer/SofortLibClientTest.php
This sneaked in during an IDE refactor
=> Fix naming of sofort client implementation

config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.BankTransferPayment.dcm.xml, src/Domain/Model/BankTransferPayment.php, tests/Unit/Domain/Model/BankTransferPaymentTest.php
While they can't be canceled after submitting the donation form,
administrators can cancel it in the Fundraising Operation Center.
=> Make Bank transfer payments cancellable

src/Domain/Model/BankTransferPayment.php, src/Domain/Model/CreditCardPayment.php, src/Domain/Model/DirectDebitPayment.php, src/Domain/Model/PayPalPayment.php, src/Domain/Model/Payment.php, src/Domain/Model/SofortPayment.php, src/UseCases/GetPayment/GetPaymentUseCase.php, tests/Unit/Domain/Model/BankTransferPaymentTest.php, tests/Unit/Domain/Model/CreditCardPaymentTest.php, tests/Unit/Domain/Model/DirectDebitPaymentTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php, tests/Unit/Domain/Model/PaymentTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php, tests/Unit/UseCases/GetPayment/GetPaymentUseCaseTest.php
https://phabricator.wikimedia.org/T305830
=> Create "GetPayment" UseCase

phpstan.neon, src/Domain/Model/BankTransferPayment.php, src/Domain/Model/CreditCardPayment.php, src/Domain/Model/DirectDebitPayment.php, src/Domain/Model/PayPalPayment.php, src/Domain/Model/Payment.php, src/Domain/Model/SofortPayment.php, src/UseCases/CreatePayment/CreatePaymentUseCase.php, src/UseCases/CreatePayment/SuccessResponse.php, tests/TestEnvironment.php, tests/TestPaymentContextFactory.php, tests/Unit/Domain/Model/BankTransferPaymentTest.php, tests/Unit/Domain/Model/CreditCardPaymentTest.php, tests/Unit/Domain/Model/DirectDebitPaymentTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php, tests/Unit/Domain/Model/PaymentTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php, tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php
The calling bounded context (donation/membership) needs to know if the
payment process is finished or if there are more steps (e.g. going to
the page of the payment providing and completing the payment there).
This will be used by the donation/membership bounded context to
determine if it should send a notification.
=> Add paymentComplete property to SuccessResponse

src/UseCases/CreateBookedPayPalPayment/CreateBookedPayPalPaymentUseCase.php, src/UseCases/CreateBookedPayPalPayment/FailingPaymentIdRepository.php, src/UseCases/CreateBookedPayPalPayment/FailureResponse.php, src/UseCases/CreateBookedPayPalPayment/SuccessResponse.php, tests/Unit/UseCases/CreateBookedPayPalPaymentUseCase/CreateBookedPayPalPaymentUseCaseTest.php
Add a new use case that'll allow people to donate by using the PayPal
app instead of the Fundraising App. This combines the "Create Payment"
and "Book Payment" functionality, but has a different internal logic:
- we only need an amount to create a one-time PayPal payments
- we verify first with PayPal that the booking request originated
with them.
- we do not support followup payments when booking (by using a failing
id generator), because these payments are never followup payments.
- we return the payment ID in the success response
This is part of https://phabricator.wikimedia.org/T304731
=> Create new booked PayPal payments

src/UseCases/CancelPayment/CancelPaymentUseCase.php, tests/Unit/UseCases/CancelPayment/CancelPaymentUseCaseTest.php
A calling class shouldn't have to worry if a payment implements the CancellablePayment interface
Ticket: https://phabricator.wikimedia.org/T305825
=> Remove exception from CancelPaymentUseCase

docker-compose.yml, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
We're using MariaDB in production and never updated our docker configs.
The new database also revealed faulty data in our DB test (DBAL needs to
insert integers in field that stores boolean value).
Run `docker-compose down -v` once on your local machine to remove the
old test database volume.
=> Switch database to MariaDB 10.4

src/PaymentContextFactory.php, tests/TestPaymentContextFactory.php
Use ORMSetup instead of the deprecated setup.
Deprecate newMappingDriver - we can now use the
DOCTRINE_CLASS_MAPPING_DIRECTORY directly
A we also need a public mapping directory for generating migrations in
https://phabricator.wikimedia.org/T305060
=> Modernize database setup

src/Domain/DomainSpecificPaymentValidator.php, src/Domain/PaymentType.php, src/Domain/PaymentValidator.php, src/UseCases/CreatePayment/CreatePaymentUseCase.php, src/UseCases/CreatePayment/PaymentCreationRequest.php, tests/Fixtures/FailingDomainSpecificValidator.php, tests/Fixtures/SucceedingDomainSpecificValidator.php, tests/Unit/Domain/PaymentValidatorTest.php, tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseBuilder.php, tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php
Inject DomainSpecificPaymentValidator through a mandatory setter
dependency in PaymentCreationRequest instead of a constructor parameter
of PaymentValidator.
This has the following benefits:
- It allows the use cases (CreateDonation/CreateMembership) to
initialize the domain-specific validation instead of relying on the
central dependency injection (FunFunFactory) to "do the right thing".
- It allows the use cases to initialize the domain specific validation
with additional parameters from the domain request. Example: The
membership minimum amount depends on the membership type.
Add PaymentType as a third parameter to the
DomainSpecificPaymentValidator interface. This will allow the
domain-specific validators to restrict payment types to certain domains
(e.g. Memberships allow only direct …
=> Change DomainSpecificPaymentValidator injection

docker-compose.yml
Using `tmpfs` for the MariaDB data directory speeds tests up by a factor
of 4x-20x, because `tmpfs` puts data in memory instead of the disk,
making IO much faster.
=> Speed up database tests

src/Domain/PaymentUrlGenerator/Sofort.php, src/Domain/PaymentUrlGenerator/SofortConfig.php, tests/Unit/Domain/PaymentUrlGenerator/SofortTest.php
Drop reasonText and use the previously-unused TranslatableDescription instead.
This makes the configuration and URL generator more consistent with the
others.
=> Improve SofortConfig constructor

src/Domain/Model/BankTransferPayment.php, src/Domain/Model/SofortPayment.php, tests/Unit/Domain/Model/BankTransferPaymentTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php
Don't use legacy keys for BankTransferPayment and SofortPayment. The
"ueb_code" key replicated a German database column name, which we use
for legacy reasons but that should not seep into template data (or API
JSON) keys
=> Change display data keys

src/Domain/Model/BookingDataTransformers/PayPalBookingTransformer.php, tests/Data/PayPalPaymentBookingData.php, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php, tests/Unit/Domain/Model/BookingDataTransformers/PayPalBookingTransformerTest.php, tests/Unit/Domain/Model/PayPalPaymentTest.php
The data export expects the status to be combined with the transaction type in order to see if it was instigated by a donor or is an automatic renewal
Ticket: https://phabricator.wikimedia.org/T307892
=> Combine status and type legacy data

config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.BankTransferPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.CreditCardPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.DirectDebitPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PayPalPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.Payment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PaymentId.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.SofortPayment.dcm.xml, src/DataAccess/DoctrinePaymentIdRepository.php, src/DataAccess/Migrations/Version20220729162240.php, src/Domain/Model/PaymentId.php, src/Services/TransactionIdFinder/DoctrineTransactionIdFinder.php, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
- database tables should be in singular
- also rename payment_id table to last_generated_payment_id to make clear this is primarily a store for IDs that have been generated before
=> Rename "payments" table to "payment"

composer.json, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.BankTransferPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.CreditCardPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.DirectDebitPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PayPalPayment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.Payment.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PaymentId.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.SofortPayment.dcm.xml, src/DataAccess/DoctrinePaymentIdRepository.php, src/DataAccess/Migrations/Version20220729162240.php, src/Domain/Model/PaymentId.php, src/Services/TransactionIdFinder/DoctrineTransactionIdFinder.php, src/UseCases/CreateBookedPayPalPayment/CreateBookedPayPalPaymentUseCase.php, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
Autogenerated the migration with `doctrine-migrations dump-schema`,
since these tables are new. Using raw SQL instead of the `Schema` object
API is OK, because trying to build the schema "from scratch" would be
error-prone.
Added doctrine-migrations as a dependency.
This is for https://phabricator.wikimedia.org/T309018
=> Add Doctrine Migration for DB schema

src/Domain/Model/LegacyBookingStatusTrait.php, src/Domain/Model/SofortPayment.php, tests/Unit/Domain/Model/SofortPaymentTest.php
The importer of our data warehousing wants to treat Sofort payments like
bank transfer payments and apparently checks the status for that :(
This change replicates code that previously was in the donation bounded
context `DomainToLegacyConverter` class.
This is a follow-up PR for https://phabricator.wikimedia.org/T314409
This will also affect the ticket
https://phabricator.wikimedia.org/T312074 in the future
=> Change legacy status of booked Sofort payments

src/Domain/Model/BankTransferPayment.php, src/Domain/Model/CancellablePayment.php, src/Domain/Model/DirectDebitPayment.php, src/UseCases/CancelPayment/CancelPaymentUseCase.php, tests/Unit/Domain/Model/BankTransferPaymentTest.php, tests/Unit/Domain/Model/DirectDebitPaymentTest.php, tests/Unit/UseCases/CancelPayment/CancelPaymentUseCaseTest.php
The backend moderators need to be able to restore
a payment that was cancelled by accident.
Ticket: https://phabricator.wikimedia.org/T318217
=> Add restore to cancellable payments

src/UseCases/CancelPayment/CancelPaymentUseCase.php, src/UseCases/CancelPayment/SuccessResponse.php, tests/Unit/UseCases/CancelPayment/CancelPaymentUseCaseTest.php
The membership context needs to know if the payment was completed in order to set it's own status so
pass it back in the response.
Ticket: https://phabricator.wikimedia.org/T318217
=> Add confirmation status to cancel success

src/UseCases/BookPayment/BookPaymentUseCase.php, src/UseCases/BookPayment/FailureResponse.php, tests/Unit/UseCases/BookPayment/FailureResponseTest.php
Add a new static constructor and a boolean getter to check if the FailureResponse is caused by an already booked payment. This will help upstream code to check against this condition without using hard-coded string messages (that might change).
Ticket: https://phabricator.wikimedia.org/T321346
=> Add paymentWasAlreadyBooked to FailureResponse

src/Domain/Model/BookingDataTransformers/PayPalBookingTransformer.php, tests/Data/PayPalPaymentBookingData.php, tests/Unit/Domain/Model/BookingDataTransformers/PayPalBookingTransformerTest.php
The 'memo' field gets populated when someone sends a PayPal donation to spenden@wikimedia.de without using the donation form. They can enter free-form text on the PayPal page, which will get sent to us in windows-1252 encoding.
This a followup for #123
Ticket: https://phabricator.wikimedia.org/T319386
=> Ignore memo field in PayPal requests

src/DataAccess/DoctrinePaymentIdRepository.php, src/DataAccess/DoctrineTypes/Euro.php, src/DataAccess/DoctrineTypes/Iban.php, src/DataAccess/DoctrineTypes/PaymentInterval.php, src/DataAccess/ScalarTypeConverter.php, src/Domain/Model/BookablePayment.php, src/Domain/Model/BookingDataTransformers/CreditCardBookingTransformer.php, src/Domain/Model/BookingDataTransformers/PayPalBookingTransformer.php, src/Domain/Model/PayPalPayment.php, src/Domain/Model/SofortPayment.php, src/Services/KontoCheck/KontoCheckBankDataGenerator.php, src/Services/TransactionIdFinder/DoctrineTransactionIdFinder.php, src/UseCases/BookPayment/BookPaymentUseCase.php, src/UseCases/CreateBookedPayPalPayment/CreateBookedPayPalPaymentUseCase.php, tests/Data/CreditCardPaymentBookingData.php, tests/Data/PayPalPaymentBookingData.php, tests/Unit/DataAccess/ScalarTypeConverterTest.php, tests/Unit/Domain/Model/BookingDataTransformers/PayPalBookingTransformerTest.php, tests/Unit/Domain/Model/SofortPaymentTest.php
This fixes a deprecation warning when using PHP 8.2 and fixes PHPStan warnings when using `intval` and `strval` on database results.
While the PHP 8.2 fix is backwards-compatible, the change from `mixed` to scalar types for the booking data is not. Create a new major release after merging.
=> Prepare for PHP 8.2

src/Services/ExternalVerificationService/PayPal/PayPalVerificationService.php, tests/System/Services/ExternalVerificationService/PayPal/PayPalVerificationServiceTest.php
Don't check receiver for now, we'll change it later to allow for
multiple receivers. We have recurring payments that have an old email
address
This is for https://phabricator.wikimedia.org/T332141
=> Emergency fix: Ignore PayPal payment receiver

phpstan-baseline.neon, src/Services/PayPal/PayPalURLGeneratorConfigReader.php, src/Services/PayPal/PayPalURLGeneratorConfigSchema.php, tests/Data/PayPalAPIURLGeneratorConfig/paypal_api_empty.yml, tests/Data/PayPalAPIURLGeneratorConfig/paypal_api_no_language.yml, tests/Data/PayPalAPIURLGeneratorConfig/paypal_api_no_plans.yml, tests/Unit/Services/PayPal/PayPalURLGeneratorConfigReaderTest.php
Use Symfony TreeBuilder checks to check the structure of the PayPal API configuration.
Add tests for missing and empty file.
This is for https://phabricator.wikimedia.org/T329161
=> Improve validation of PPL API config

composer.json, phpstan.neon, src/DataAccess/DoctrinePaymentRepository.php, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
Doctrine ORM 2.16 introduced a check for different Entities with the same ID in the `persist` method. Previously, we checked for an exception thrown by the database layer (`flush` method), now we also need to check on persist.
=> Additional error handling for duplicate IDs

config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PayPalOrder.dcm.xml, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PayPalSubscription.dcm.xml, src/DataAccess/Migrations/Version20231012164127.php, src/Domain/Model/PayPalOrder.php, src/Services/PayPal/PayPalPaymentProviderAdapter.php, tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php, tests/Unit/Domain/Model/PayPalOrderTest.php, tests/Unit/Services/PayPal/PayPalPaymentProviderAdapterTest.php
This prepares the database layer for the two-step process of creating a
one-time-payment (Order) with the PayPal API:
- The first API call creates the Order, returning an Order ID
- When the user comes back from the payment provider to the return URL,
the URL will contain the Order ID parameter and we'll have to make
another API request to *capture* the order, which will return a
transaction ID. We won't *book* the payment (that's still done in the
IPN handling), but we will store the returned transaction ID in the
PayPalOrder class, so the notification code can lookup the payment via
transaction ID.
This change also introduces indexes for the `PayPalPaymentIdentifier`
subclasses `PayPalOrder` and `PayPalSubscription` and creates a database migration.
Ticket: …
=> Prepare Database for One-Time payments

src/Services/PaymentProviderAdapterFactoryImplementation.php
Modify the PaymentProviderAdapterFactoryImplementation to create the
default (i.e. "do nothing") implementation for PayPal payments.
This fixes a bug where the payment tries to contact the PayPal API even
when the feature should be turned off
=> Allow legacy paypal adapter

composer.json, src/Services/PaymentUrlGenerator/SofortURLGenerator.php, tests/Fixtures/FakeUrlAuthenticator.php, tests/Unit/Services/PaymentUrlGenerator/CreditCardURLGeneratorTest.php, tests/Unit/Services/PaymentUrlGenerator/LegacyPayPalURLGeneratorTest.php, tests/Unit/Services/PaymentUrlGenerator/SofortURLGeneratorTest.php
Commit 744a69815dbc5b017ebeff6e2a38774dff475954 introduced an error
where the `SofortURLGenerator` appended the wrong parameters to the
notification URL (`accessToken` instead of `updateToken`). This commit
fixes SofortURLGenerator.
This commit also changes the generated value in FakeUrlAuthenticator
because it generates *parameters* and not only *tokens*. This results in
changes for all URL Generator classes.
This fixes https://phabricator.wikimedia.org/T350149
=> Fix SofortURLGenerator

src/Services/TransactionIdFinder/DoctrineTransactionIdFinder.php
Querying with the default STRING parameter type makes the database
ignore the index, which leads to a full table scan, which blocks the
database.
=> Fix performance of DoctrineTransactionIdFinder

src/Domain/PaymentValidator.php, src/UseCases/CreatePayment/CreatePaymentUseCase.php, tests/Unit/Domain/PaymentValidatorTest.php, tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php
Instead of relying on outside factors or validation, make the rule that
Sofort payments can only be one-time (because the API and the provider
does not *allow* recurring payments) a validation rule.
https://phabricator.wikimedia.org/T350848
=> Validate interval for Sofort payments

composer.json
Allow for any minor version of fun-validators
Remove unused freezable-value-object
Ticket: https://phabricator.wikimedia.org/T350676
=> Fix composer version constraints

.github/dependabot.yml
- this change will prevent dependabot from creating a single pull request for every patch version update of a dependency but group them (like in many other of our repos now)
=> Group patch updates

src/Commands/CreateSubscriptionPlansCommand.php, src/Commands/ListSubscriptionPlansCommand.php, src/PaymentContextFactory.php, tests/System/Services/ExternalVerificationService/PayPal/PayPalVerificationServiceTest.php, tests/Unit/Domain/Model/BookingDataTransformers/CreditCardBookingTransformerTest.php, tests/Unit/Domain/Model/BookingDataTransformers/PayPalBookingTransformerTest.php, tests/Unit/Services/PayPal/PayPalPaymentProviderAdapterTest.php, tests/Unit/Services/PaymentUrlGenerator/CreditCardURLGeneratorTest.php, tests/Unit/UseCases/CreateBookedPayPalPaymentUseCase/CreateBookedPayPalPaymentUseCaseTest.php, tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php, tests/Unit/UseCases/CreateSubscriptionPlansForProduct/CreateSubscriptionPlansForProductTest.php
Increase coverage by adding `@covers` tags for value objects in tests
where those value objects are used.
=> Add coverage tags

composer.json
With the release of 2.0 Deptrac can now be installed regularly with
composer, omitting the "shim".
Dependency tracking still passes, no other changes needed.
=> Update Deptrac to 2.0

composer.json, config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.FeeChangePayment.dcm.xml, migrations-db.php, migrations.php, src/DataAccess/Migrations/Version20250916164428.php
- Add a table name to the mapping file to conform with our other table
names.
- Add migration configuration files
- Add migration that creates the `payment_fee_change` table
This is a followup for #215
Ticket: https://phabricator.wikimedia.org/T395015
**Integration instructions:** When updating the fundraising application, re-run `make generate-database-schema` to refresh the SQL file. That will take care of the renamed table.
=> Add migration to create fee change table
