wmde/fundraising-payments

src/Domain/BankDataValidator.php
tests/Unit/Domain/BankDataValidatorTest.php

Moving code out of AddDonationValidatorTest (in the DonationContext
repo) into this repo.

Validate bank name length

---

Makefile
src/Domain/BankDataValidationResult.php
src/Domain/BankDataValidator.php
src/Domain/PaymentDataValidationResult.php
src/Domain/PaymentDataValidator.php
tests/Unit/Domain/BankDataValidatorTest.php

Bring the code more in line with the patterns found in the Donation and
Membership contexts: A clearly defined validation source and and message
(type of violation).
The BankDataValidatorTest now checks for those.

Refactor validation results

---

.travis.yml
Makefile
composer.json

Also updates the Makefile to make it more consistent with the other bounded contexts.

[DNM] Update freezable value object

---

.travis.yml
Makefile
composer.json
docker-compose.yml

* Move Fundraising Frontend Docker image to Gitlab (https://phabricator.wikimedia.org/T274115)
* Add coverage to phpunit (https://phabricator.wikimedia.org/T274014)
* Remove covers validator
* Remove Docker dependencies from CI

Tooling Maintenance

---

src/Domain/PaymentUrlGenerator/PayPal.php
tests/Unit/Domain/PaymentUrlGenerator/PayPalTest.php

https://phabricator.wikimedia.org/T276215

[DNM] Add invoice ID to Paypal transactions

---

src/Domain/Model/BankTransferPayment.php
src/Domain/Model/CreditCardPayment.php
src/Domain/Model/DirectDebitPayment.php
src/Domain/Model/PayPalPayment.php
src/Domain/Model/PaymentMethod.php
src/Domain/Model/PaymentWithoutAssociatedData.php
src/Domain/Model/SofortPayment.php

To be used as part of https://github.com/wmde/fundraising-memberships/pull/69
Related ticket: https://phabricator.wikimedia.org/T276941
Also related: https://phabricator.wikimedia.org/T192323

Add paymentCompleted method to PaymentMethod

---

.scrutinizer.yml

Update Scrutinizer configuration

Use new Scrutinizer engine

---

src/Domain/PaymentDataValidator.php

We no longer need to expose this as amount validation is performed on the front end
Ticket: https://phabricator.wikimedia.org/T239349

Make validator validAmount method private

---

src/DataAccess/Sofort/Transfer/Request.php
src/DataAccess/Sofort/Transfer/SofortClient.php
src/DataAccess/Sofort/Transfer/SofortLibSofortClient.php
src/Domain/PaymentUrlGenerator/CreditCard.php
src/Domain/PaymentUrlGenerator/CreditCardConfig.php
src/Domain/PaymentUrlGenerator/PayPal.php
src/Domain/PaymentUrlGenerator/PayPalConfig.php
src/Domain/PaymentUrlGenerator/Sofort.php
src/Domain/PaymentUrlGenerator/SofortConfig.php
tests/Fixtures/ExceptionThrowingSofortSofortClient.php
tests/Fixtures/SofortSofortClientSpy.php
tests/Unit/DataAccess/Sofort/Transfer/SofortLibClientTest.php
tests/Unit/Domain/PaymentUrlGenerator/CreditCardTest.php
tests/Unit/Domain/PaymentUrlGenerator/PayPalConfigTest.php
tests/Unit/Domain/PaymentUrlGenerator/PayPalTest.php
tests/Unit/Domain/PaymentUrlGenerator/SofortTest.php

https://phabricator.wikimedia.org/T285923

Add gateway locales

---

composer.json
src/Domain/LessSimpleTransferCodeGenerator.php
tests/Unit/Domain/Model/PayPalPaymentTest.php

Update PHPStan and coding standard and adapt code

Update dev dependencies

---

.travis.yml
Makefile
phpstan-baseline.neon
phpstan.neon
src/Domain/BankDataValidator.php
src/Domain/ChecksumGenerator.php
src/Domain/DefaultPaymentDelayCalculator.php
src/Domain/IbanBlocklist.php
src/Domain/LessSimpleTransferCodeGenerator.php
src/Domain/LessSimpleTransferCodeValidator.php
src/Domain/Model/BankData.php
src/Domain/PaymentDataValidator.php

Add a baseline file with current errors. This will force us to write properly annotated and typed code in the future

Use PHPStan Level 9

---

.travis.yml
docker-compose.debug.yml

Only needed until https://travis-ci.community/t/php-8-1-support/12439/20
is fixed

Add workaround for Travis PHP 8.1 support

---

Makefile
build/app/Dockerfile
build/wait-for-it.sh
composer.json
config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PaymentID.dcm.xml
docker-compose.debug.yml
docker-compose.yml
phpstan-baseline.neon
src/DataAccess/DoctrinePaymentIDRepository.php
src/DataAccess/DoctrinePaymentRepository.php
src/Domain/Model/PaymentID.php
src/Domain/Repositories/PaymentIDRepository.php
tests/Fixtures/StaticPaymentIDRepository.php
tests/Integration/DataAccess/DoctrinePaymentIDRepositoryTest.php
tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
tests/TestEnvironment.php
tests/TestPaymentContextFactory.php
tests/Unit/Domain/LessSimpleTransferCodeGeneratorTest.php

This adds a new schema, repository and use case
that allows donations or memberships to request a
new unique payment ID in order to create a
payment entity.
Also added is the required infrastructure for
the Doctrine annotation mapping.
Ticket: https://phabricator.wikimedia.org/T301115

Add PaymentIDRepository

---

config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.BankTransferPayment.dcm.xml
config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.Payment.dcm.xml
src/Domain/Model/BankTransferPayment.php
tests/Cli/InspectorGeneratorCommand.php
tests/Inspectors/BankTransferPaymentInspector.php
tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
tests/Unit/Domain/Model/BankTransferPaymentTest.php

* Add Bank Transfer Doctrine mapping
* Refactor BankTransferPayment model
* Add BankTransferPaymentInspector
https://github.com/wmde/fundraising-payments/pull/68 Should be merged before this.
Ticket: https://phabricator.wikimedia.org/T301809

Refactor bank transfer

---

phpunit.xml.dist
src/DataAccess/DoctrineTypes/Euro.php
src/DataAccess/DoctrineTypes/Iban.php
src/DataAccess/DoctrineTypes/PaymentInterval.php
src/DataAccess/DoctrineTypes/PaymentReferenceCode.php
tests/System/Services/KontoCheck/KontoCheckLibraryInitializationExceptionTest.php
tests/Unit/DataAccess/Sofort/Transfer/RequestTest.php
tests/Unit/Domain/RandomPaymentReferenceGeneratorTest.php
tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php

Add annotations for covered and uncovered (trivial classes)
Add tests for missing coverage
Run system test suite

Increase code coverage

---

phpstan.neon
src/DataAccess/DoctrineTypes/PaymentReferenceCode.php
src/Domain/Model/PaymentReferenceCode.php
src/Domain/Model/SofortPayment.php
tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
tests/Unit/Domain/Model/PaymentReferenceCodeTest.php
tests/Unit/Domain/Model/SofortPaymentTest.php

This adds the tests that were overlooked in https://github.com/wmde/fundraising-payments/pull/69
Ticket: https://phabricator.wikimedia.org/T301806

Sofort Tidy Ups

---

src/Domain/PaymentUrlGenerator/AdditionalPaymentData.php
src/Domain/PaymentUrlGenerator/CreditCard.php
src/Domain/PaymentUrlGenerator/CreditCardConfig.php
src/Domain/PaymentUrlGenerator/NullGenerator.php
src/Domain/PaymentUrlGenerator/PayPal.php
src/Domain/PaymentUrlGenerator/PayPalConfig.php
src/Domain/PaymentUrlGenerator/PaymentProviderURLGenerator.php
src/Domain/PaymentUrlGenerator/PaymentURLFactory.php
src/Domain/PaymentUrlGenerator/RequestContext.php
src/Domain/PaymentUrlGenerator/Sofort.php
src/Domain/PaymentUrlGenerator/SofortConfig.php
src/Domain/PaymentUrlGenerator/TranslatableDescription.php
tests/Unit/Domain/PaymentUrlGenerator/CreditCardTest.php
tests/Unit/Domain/PaymentUrlGenerator/NullGeneratorTest.php
tests/Unit/Domain/PaymentUrlGenerator/PayPalConfigTest.php
tests/Unit/Domain/PaymentUrlGenerator/PayPalTest.php
tests/Unit/Domain/PaymentUrlGenerator/PaymentURLFactoryTest.php
tests/Unit/Domain/PaymentUrlGenerator/SofortTest.php

https://phabricator.wikimedia.org/T302424

Refactor url generators

---

config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.DirectDebitPayment.dcm.xml
src/Domain/Model/BankTransferPayment.php
src/Domain/Model/CancellablePayment.php
src/Domain/Model/DirectDebitPayment.php
src/Domain/Model/Payment.php
src/UseCases/CancelPayment/CancelPaymentUseCase.php
src/UseCases/CancelPayment/FailureResponse.php
src/UseCases/CancelPayment/SuccessResponse.php
tests/Fixtures/PaymentRepositorySpy.php
tests/Inspectors/DirectDebitPaymentInspector.php
tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php
tests/Unit/UseCases/CancelPayment/CancelPaymentUseCaseTest.php

Ticket: https://phabricator.wikimedia.org/T304725

Cancel payment

---

composer.json
src/Services/ExternalVerificationService/ExternalVerificationServiceFactory.php
src/Services/ExternalVerificationService/PayPal/PayPalVerificationService.php
src/Services/ExternalVerificationService/SucceedingVerificationService.php
src/UseCases/BookPayment/BookPaymentUseCase.php
src/UseCases/BookPayment/VerificationResponse.php
src/UseCases/BookPayment/VerificationService.php
src/UseCases/BookPayment/VerificationServiceFactory.php
tests/System/Services/ExternalVerificationService/PayPal/PayPalVerificationServiceTest.php
tests/Unit/UseCases/BookPayment/BookPaymentUseCaseTest.php

* Add interfaces for service factory and verifier
* Add ExternalVerificationService implementation
* Add PayPal and Succeeding verification services
* Add tests

Payment provider callback

---

tests/System/Services/ExternalVerificationService/ExternalVerificationServiceFactoryTest.php

Follow up that adds tests to make coverage happy
Ticket: https://phabricator.wikimedia.org/T304827

Add tests for ExternalVerificationServiceFactory

---

src/Domain/DomainSpecificPaymentValidator.php
src/Domain/PaymentTypes.php
src/Domain/PaymentUrlGenerator/PaymentURLFactory.php
src/Domain/PaymentUrlGenerator/UrlGeneratorFactory.php
src/Domain/PaymentValidator.php
src/UseCases/CreatePayment/CreatePaymentUseCase.php
tests/Fixtures/FailingDomainSpecificValidator.php
tests/Fixtures/FailingIbanValidator.php
tests/Fixtures/SequentialPaymentIDRepository.php
tests/Fixtures/SucceedingDomainSpecificValidator.php
tests/Fixtures/SucceedingIbanValidator.php
tests/Unit/Domain/PaymentValidatorTest.php
tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseBuilder.php
tests/Unit/UseCases/CreatePayment/CreatePaymentUseCaseTest.php

Validate amount, interval and payment type.
This class is for moving the validation out of the CreatePayment use
case and for creating a standalone validation use case.
This is for https://phabricator.wikimedia.org/T305235

Add Payment Validator class

---

tests/Unit/Domain/Model/PaymentTest.php

Abstract payment class now has 100% coverage again

Add tests for Payment

---

src/PaymentContextFactory.php
tests/TestPaymentContextFactory.php

This is for https://phabricator.wikimedia.org/T312080

Use getDoctrineMappingPaths in context factory

---

composer.json
config/DoctrineClassMapping/WMDE.Fundraising.PaymentContext.Domain.Model.PaymentReferenceCode.dcm.xml
phpstan-baseline.neon
tests/Integration/DataAccess/DoctrinePaymentRepositoryTest.php

- Resolve the errors
Ticket: https://phabricator.wikimedia.org/T356744

Update Doctrine ORM and DBAL

---

.scrutinizer.yml
.travis.yml

Use newer build image in Scrutinizer config
Change how we upload coverage in .travis.yml

Fix Scrutinizer

---

src/Domain/Model/BookingDataTransformers/CreditCardBookingTransformer.php
src/Domain/Model/Payment.php
src/UseCases/GetPayment/GetPaymentUseCase.php

- This will avoid some phpstan troubles when using the payment bounded context

Convert mixed to scalar type

---

.drone.yml
Makefile
composer.json

Update all Symfony dependencies to 7.0
Checked the CHANGELOG files of each dependency and we don't have any
code that is affected by breaking changes
Ticket: https://phabricator.wikimedia.org/T355689

Update Symfony to 7.0

---

src/Domain/Model/LegacyBookingStatusTrait.php
src/Domain/Model/LegacyDataTransformer.php
src/Domain/Model/LegacyPaymentData.php
src/Domain/Model/LegacyPaymentStatus.php
src/Domain/Model/Payment.php
src/Services/PaymentUrlGenerator/LegacyPayPalURLGenerator.php
src/UseCases/GetPayment/GetPaymentUseCase.php
tests/Unit/UseCases/GetPayment/GetPaymentUseCaseTest.php

- Use more scalar types
- Add Information about LegacyPaymentData

improve types

---

.woodpecker/ci.yml

This will isolate MySQL in this pipeline from other pipelines

Change MySQL folder in /dev/shm

---

.woodpecker/ci.yml

the pipeline needs to be isolated from other pipelines, the name should be payments here and not memberships
Merged this too soon: https://github.com/wmde/fundraising-payments/pull/167

Fix name of the temporary filesystem

---

.github/dependabot.yml
Makefile
README.md
docker-compose.yml
docs/paypal_api.md

- Change Makefile
- Remove deprecated version property
Ticket: https://phabricator.wikimedia.org/T317957

Prepare for docker compose v2

---

.gitignore
composer.json
composer.lock

- Reason: Repo https://github.com/wmde/fundraising-donations requires `v5` of https://github.com/wmde/fun-validators
Ticket: https://phabricator.wikimedia.org/T387207

Use `fun-validators` v5

---

composer.json
composer.lock

This takes care of the deprecation notice when installing dependencies
with composer.
Update the dependencies.

Replace qossmic/deptrac with deptrac/deptrac
